### PR TITLE
Update to m-fluido 2.0.0-M5

### PR DESCRIPTION
**Pull request by kwin**
https://issues.apache.org/jira/browse/MSKINS-207

### CODE REVIEW

**Comment by michael-o** [comment]
This needs to go hand in hand with Maven Site Plugin, but consider that there might be plugins which aren't compatible anymore. They won't fail, but they might produce garbage output.

**Comment by michael-o** [comment]
> m-site-p is already on version 4.0.0-M6,
> 
> https://github.com/apache/maven-site/blob/4624b5cb3301670c7faac8d838844f0ba35bdfc9/pom.xml#L116

Then you should wit for M5 of the skin.

**Comment by kwin** [comment]
It is broken currently! Is it worse with m3 or better? At least the table in https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html looks correct with m3 (and severely broken in 1.11.1). We can easily upgrade to M5 once released....

**Comment by michael-o** [comment]
> It is broken currently! Is it worse with m3 or better? At least the table in https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html looks correct with m3 (and severely broken in 1.11.1). We can easily upgrade to M5 once released....

Well, verbatim source is broken as well. If you can wait two days than you can go to M5 directly.

**Comment by michael-o** [comment]
> We are still on Doxia 2.0.0-M3 (
> 
> https://github.com/apache/maven-site/blob/4624b5cb3301670c7faac8d838844f0ba35bdfc9/pom.xml#L78
> ) therefore probably not affected by https://issues.apache.org/jira/browse/MSKINS-221, or am I missing something?

We are because MSITE 4.0.0-M6 includes Doxia 2.0.0-M6.

**Comment by slawekjaranowski** [comment]
I simply built a site with this change and tables looks more better.

**Comment by hboutemy** [comment]
IIUC, not highlighted is less broken than table :)

**Comment by slachiewicz** [comment]
i've added change to bump to fluido-2.0.0-M5 to easier test and help with release vote

**Review by michael-o — CHANGES_REQUESTED** [review]
M5 should be available in a hour or so. Then upgrade to it and merge this one.

**Comment by slachiewicz** [comment]
for all changes like here with Doxia, where we may change generated output - maybe would good to write gha pipeline to show diff before/after introduced change - visible here in gh report? This is something  that we now do manually to verify dep upgrade or validate release.

**Comment by michael-o** [comment]
> for all changes like here with Doxia, where we may change generated output - maybe would good to write gha pipeline to show diff before/after introduced change - visible here in gh report? This is something that we now do manually to verify dep upgrade or validate release.

that would be really really awesome. For now, I do this manually.

**Pull request merged**
