### PR TITLE
MSITE-909 - Added new Site skin information to documentation

### PR DESCRIPTION
**Pull request by stevecrox**
Added new Site skin information to documentation

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Review by michael-o — CHANGES_REQUESTED** [review]
The commit message does not correspond to the actual changeset.

**Comment by michael-o** [comment]
Change looks good.

**Comment by stevecrox** [comment]
Is there anything outstanding for me to do?

**Comment by jira-importer** [comment]
Resolve #1038

**Pull request merged**
