### PR TITLE
SVN page is 404

### PR DESCRIPTION
**Pull request by elharo**
@hboutemy

### CODE REVIEW

**Comment by michael-o** [comment]
Question is whether the file is completely gone or not.

**Comment by elharo** [comment]
Google search only finds it here:

http://khmarbaise.github.io/maven-site/fluido/developers/conventions/svn.html

**Comment by elharo** [comment]
Thanks. Looks like I'm not listed as a committer in this repo yet so someone else will have to merge.

**Comment by slachiewicz** [comment]
Please try to push to gitbox repo instead of GitHub

**Comment by olamy** [comment]
@elharo have you been there https://gitbox.apache.org/setup/?
@slachiewicz why? we can definitely push to github

**Comment by elharo** [comment]
Yes, I have. For some reason it doesn't like my username or password. I need to figure that out.

**Comment by elharo** [comment]
OK, got the right username/password. I think now I'm waiting for somebody or some automated system to send me an invite to the apache org. Or do I have to request that somewhere?

**Pull request merged**
