### PR TITLE
Resolution open issues MNGSITE-292 :  Update the mini guide to creating archetypes to Archetype 2.x

### PR DESCRIPTION
**Pull request by greslier**
The mini-guide to creating archetypes in version 1.x should be updated to match Archetype 2.x (the essential difference being the archetype-metadata.xml descriptor).

### CODE REVIEW

**Comment by khmarbaise** [comment]
Would you please so kind to make commit message in english....

**Comment by khmarbaise** [comment]
Can you please squash your commits and rebase against master....

**Comment by Sam-Kruglov** [comment]
`xsi:schemaLocation` has two identical entries?

```
xsi:schemaLocation="http://maven.apache.org/plugins/maven-archetype-plugin/archetype-descriptor/1.0.0
                                           http://maven.apache.org/xsd/archetype-descriptor-1.0.0.xsd
                                           http://maven.apache.org/plugins/maven-archetype-plugin/archetype-descriptor/1.0.0"
```

**Comment by Sam-Kruglov** [comment]
two `artifactId` entries on line 67?

**Comment by greslier** [comment]
I have resolved the problems of duplicate. Thank for yours returns.

**Comment by slachiewicz** [comment]
Thank you @greslier for contribution, changes should be visible now.

**Pull request closed without merging**
