### PR TITLE
[MNGSITE-502] Document profile activation based on packaging

### PR DESCRIPTION
**Pull request by kwin**
Improve structure within profile activation documentation

### CODE REVIEW

**Comment by cstamas** [comment]
@delanym

**Review by cstamas — APPROVED** [review]

**Comment by delanym** [comment]
Seems the contents are broken now - none of the links work: https://maven.apache.org/guides/introduction/introduction-to-profiles.html

**Review by Joumax14 — COMMENTED** [review]
I agree

**Comment by kwin** [comment]
The issue with the broken TOC links needs to be fixed in fluido most probably: https://issues.apache.org/jira/browse/MSKINS-229

**Pull request merged**
