### PR TITLE
MNGSITE-527 broken link to settings-1.3.0.xsd

### PR DESCRIPTION
**Pull request by froque**
JIRA issue: https://issues.apache.org/jira/browse/MNGSITE-527

### CODE REVIEW

**Review by gnodet — CHANGES_REQUESTED** [review]
If we are to publish 4.0.0-alpha related XSDs, we'll also miss:
  * maven-4.1.0.xsd
  * core-extensions-1.2.0.xsd
  * plugin-1.1.0.xsd

**Comment by froque** [comment]
Running `mvn verify` on latest maven master only creates a `settings-1.3.0.xsd`. How can I create those 3 files ?

**Comment by ditbace** [comment]
Thanks

**Comment by ditbace** [comment]
I don't know that is what I'm trying to do.

**Comment by gnodet** [comment]
The two missing XSDs should now be available by building maven master branch.

**Comment by gnodet** [comment]
The `plugin-[version].xsd` schemas are currently not published, so don't bother with those.

**Review by gnodet — APPROVED** [review]

**Comment by gnodet** [comment]
I'm slightly worried about publishing unstable XSDs.  This may cause problem is the next 4.0.0 alpha/beta/milestone release does actually change it.  Users may have the schema cached by their IDE already.  A safe way would be to bump the version of the schemas if they changed in a future release, irrespective of its alpha status.  Another one would be to publish those with `-alpha-8` or maybe just `alpha` in their file name, so something like `maven-4.1.0-alpha-8.xsd`... ?

**Comment by gnodet** [comment]
Note that adding `-alpha-8` in the file names won't exactly fix the existing broken links.
But at least, it provides an easy fix...

**Comment by slawekjaranowski** [comment]
Should we have license headers in files? 
Does missing license will break site builds?

**Review by slawekjaranowski — CHANGES_REQUESTED** [review]
```
mvn verify 

....

[WARNING] Files with unapproved licenses:
  content/resources/xsd/core-extensions-1.2.0-alpha-8.xsd
  content/resources/xsd/maven-4.1.0-alpha-8.xsd
  content/resources/xsd/assembly-2.2.0.xsd
  content/resources/xsd/settings-1.3.0-alpha-8.xsd
  content/resources/xsd/assembly-component-2.2.0.xsd
...

**Comment by slawekjaranowski** [comment]
By the way ... maybe we should create html page at https://maven.apache.org/xsd/ with description for which component and version specific xsd should be used

another idea - add to xsd comments component and version

of course all for next PRs

**Comment by gnodet** [comment]
> Should we have license headers in files? Does missing license will break site builds?

Those files are generated.  Not sure if the old ones have been manually edited to add the header before publication or if the generation somehow changed in modello...

> By the way ... maybe we should create html page at https://maven.apache.org/xsd/ with description for which component and version specific xsd should be used
> 
> another idea - add to xsd comments component and version
> 
> of course all for next PRs

I'd like to avoid maintaining the whole list of schemas manually.  I think using a `.htaccess` could be leveraged to provide a `readme.html` to display on top of the listing. See [apache mod_autoindex](https://httpd.apache.org/docs/2.0/mod/mod_autoindex.html#indexoptions)

**Review by michael-o — APPROVED** [review]

**Review by slawekjaranowski — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #1335

**Pull request merged**
