### PR TITLE
[MNGSITE-496] Outline all means to load extensions and clarify

### PR DESCRIPTION
**Pull request by kwin**
differences

### CODE REVIEW

**Review by cstamas — APPROVED** [review]
But POM has extensions element as well https://maven.apache.org/pom.html#Extensions

**Comment by cstamas** [comment]
Maybe state clearly that [afterSessionStart](https://github.com/apache/maven/blob/master/maven-core/src/main/java/org/apache/maven/AbstractMavenLifecycleParticipant.java#L63) does NOT work in "late" mode for obvious reasons.

**Comment by kwin** [comment]
> But POM has extensions element as well https://maven.apache.org/pom.html#Extensions

I think I mentioned those at https://github.com/apache/maven-site/pull/326/files#diff-bcbf6d6b4afe0d44d1c378f922812615b44429cb439b08fcb503e47446c138f4R83.

**Comment by kwin** [comment]
> Maybe state clearly that [afterSessionStart](https://github.com/apache/maven/blob/master/maven-core/src/main/java/org/apache/maven/AbstractMavenLifecycleParticipant.java#L63) does NOT work in "late" mode for obvious reasons.

Is that not clear enough: https://github.com/apache/maven-site/pull/326/files#diff-d57f2ffce98d7dc59a0359835112b62a6bb7213f279eae4c60f67a6a9ef5638fR125? For me that is an aspect for extension writers and not so much for extension consumers?

**Comment by cstamas** [comment]
oh, i missed those, sorry (I hate archaic APT format). Yes, is important for ext authors, not much for consumers.

**Comment by jira-importer** [comment]
Resolve #1055

**Pull request merged**
