### PR TITLE
On branch edburns-cognitive-tax-nit-01 Don't make me think: use graph…

### PR DESCRIPTION
**Pull request by edburns**
…ic in addition to text.

modified:   content/apt/guides/introduction/introduction-to-dependency-mechanism.apt

- When reading "A, B, and C are defined as A -> B -> C -> D 2.0 and A ->
  E -> D 1.0, then D 1.0 will b" my eyes glazed over.  I added a graphic
  to supplement the existing text.

### CODE REVIEW

**Comment by mkarg** [comment]
> Can you squash this into a single commit? Thanks.

Why should he invest time into doing that? Any committer can simply click on that green arrow button to do that *on the fly*:

image

**Comment by elharo** [comment]
You didn't take that screenshot in this repo. It doesn't allow squash commits. I don't know why.

**Comment by mkarg** [comment]
> You didn't take that screenshot in this repo. It doesn't allow squash commits. I don't know why.

I am pretty sure there is a PMC that could simply instruct their administrators to enable this option, even on *this* repo.

**Comment by elharo** [comment]
You'd have to ask the PMC about that. Some folks object to squash and merge. Not my call.

**Comment by edburns** [comment]
I can certainly squash, no problem at all.

**Comment by edburns** [comment]
@mkarg @elharo Squashed into  79d956f6a .

**Pull request merged**
