### PR TITLE
Link to the matrix

### PR DESCRIPTION
**Pull request by jbaruch**
Re-added a link to the matrix back. It's a good and important source of information.

### CODE REVIEW

**Comment by mosabua** [comment]
We do not want to link to any external source for comparison that is not managed by all stakeholders and we do not want to manage to be an impartial source. We therefore just link to the different pages of the different products. The rest is up to the user.

**Comment by mosabua** [comment]
And as such -1 ... do not merge imho.

**Comment by jbaruch** [comment]
well, not that I am surprised. Regarding "not managed by all stakeholders" - this is a lie. @olamy and @brianf (the authors of the original matrix) are invited admins of the comparison matrix github repo.

**Comment by mosabua** [comment]
Neither @brianf nor @olamy have interest nor time from my conversations with them to make sure the matrix stays independent and neutral. As such it is NOT impartial.  E.g. just look at the commit history.

https://github.com/binary-repositories-comparison/binary-repositories-comparison.github.io/commits/master

Feel free to put the matrix on the jfrog website and link from there, but the Maven project should imho stay out of this political tit for tat.

Nothing stops you from linking to the matrix from the jfrog site or any other website.

**Comment by jbaruch** [comment]
It takes the exact amount of time and effort as the previous matrix on
codehaus.
Re the commit history, that's ridiculous claim. The migration from codehaus
took some commits, obviously. And the fact that Archiva and Nexus
shareholders didn't update their columns is not because they can't. They
did it for years and I can't see a single reason why they'd want to stop.
Just merge this PR and see how they both update the content.

**Comment by stephenc** [comment]
As a member of the PMC:

The PMC has discussed this. The decision of the PMC is that the Apache Maven site will present an alphabetically sorted list of repository managers only.

**Pull request closed without merging**
