### PR TITLE
[MNG-6994] follow-up APT syntax fixes

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Comment by kwin** [comment]
Follow up to #205

**Review by slachiewicz — APPROVED** [review]

**Comment by kwin** [comment]
Can you merge this soon? The current live version has some flaws which make these pages very unpleasant to read.

**Comment by hboutemy** [comment]
thank you: such fixes are so useful

**Comment by jira-importer** [comment]
Resolve #997

**Pull request merged**
