### PR TITLE
Bump Maven Site Plugin AND Maven Fluido Skin

### PR DESCRIPTION
**Pull request by michael-o**
Both need to be updated in tandem to get proper rendering results.

Addresses one of the issues from https://the-asf.slack.com/archives/C7Q9JB404/p1715479275966359

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
We should check it ... by other hands
My test:
 - `What is Maven?`, `Maven Extensions` - is empty - markdown problems?
 - `Release Notes` - is almost empty - looks like macros not working
 
I not checked all pages 😄

**Review by slawekjaranowski — CHANGES_REQUESTED** [review]
more testing required ... I see empty pages

**Comment by michael-o** [comment]
> We should check it ... by other hands My test:
> 
>     * `What is Maven?`, `Maven Extensions` - is empty - markdown problems?
> 
>     * `Release Notes` - is almost empty - looks like macros not working
> 
> 
> I not checked all pages 😄

It is broken, the parsers are strict now for sections:
```patch
D:\Entwicklung\Projekte\maven-site [bump-site-and-fluido-version ≡ +0 ~2 -0 !]> git diff content/markdown/what-is-maven.md
diff --git a/content/markdown/what-is-maven.md b/content/markdown/what-is-maven.md
index 9a8f73d4..bb848972 100644
--- a/content/markdown/what-is-maven.md
+++ b/content/markdown/what-is-maven.md
@@ -1,4 +1,4 @@
-## Introduction
+# Introduction
 <!--
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
```

**Comment by michael-o** [comment]
> We should check it ... by other hands My test:
> 
>     * `What is Maven?`, `Maven Extensions` - is empty - markdown problems?
> 
>     * `Release Notes` - is almost empty - looks like macros not working
> 
> 
> I not checked all pages 😄

Which release notes are empty?

**Comment by michael-o** [comment]
@slawekjaranowski This should fix it. The Markdown files were logically incorrect.

**Comment by slawekjaranowski** [comment]
release history:
image

**Comment by slawekjaranowski** [comment]
> 
> It is broken, the parsers are strict now for sections:
>

So the build should fail when page is not generated at all due to error.

**Comment by slawekjaranowski** [comment]
alignment also changed:
image

**Comment by michael-o** [comment]
> > It is broken, the parsers are strict now for sections:
> 
> So the build should fail when page is not generated at all due to error.

@kwin, WDYT?

**Comment by michael-o** [comment]
> alignment also changed: image

Comes from https://issues.apache.org/jira/browse/MSKINS-230. We need to decide whether we want to keep it it have bootstrap style enforced.

**Comment by michael-o** [comment]
> release history: image

Done.

**Comment by michael-o** [comment]
> > It is broken, the parsers are strict now for sections:
> 
> So the build should fail when page is not generated at all due to error.

From the top of my head I have no idea because this is now only with Markdown and most of the parsing is done with Flexmark anyway. But some of the strictness has been added by @kwin recently. The purpose is that the output should be parseable again from a Doxia point of view. Broken output cannot be parsed :-(

**Comment by kwin** [comment]
I have not deliberately changed anything about being more strict with section nesting, I think we should still allow starting with an h2. Could be an unintended side effect of fixing the nesting levels. Do we have a minimum example in MD? Any warning emitted?

**Comment by michael-o** [comment]
> I have not deliberately changed anything about being more strict with section nesting, I think we should still allow starting with an h2. Could be an unintended side effect of fixing the nesting levels. Do we have a minimum example in MD? Any warning emitted?

There is no warning, just no output.

**Comment by michael-o** [comment]
I have found another severe bug I need to report: As soon as auto anchors are enabled title for the document is not extracted/filled, if you do this then it works again:
```
diff --git a/doxia-site-renderer/src/main/java/org/apache/maven/doxia/siterenderer/DefaultSiteRenderer.java b/doxia-site-renderer/src/main/java/org/apache/maven/doxia/siterenderer/DefaultSiteRenderer.java
index 544b6b9..b6a7d1d 100644
--- a/doxia-site-renderer/src/main/java/org/apache/maven/doxia/siterenderer/DefaultSiteRenderer.java
+++ b/doxia-site-renderer/src/main/java/org/apache/maven/doxia/siterenderer/DefaultSiteRenderer.java
@@ -330,7 +330,6 @@ public class DefaultSiteRenderer implements Renderer {
             if (!isConfigured) {
                 // DOXIASITETOOLS-146 don't render comments from source markup
                 parser.setEmitComments(false);
-                parser.setEmitAnchorsForIndexableEntries(true);
             }

             // TODO: DOXIA-111: the filter used here must be checked generally.
```

**Comment by michael-o** [comment]
I will hold off new releases until this issues is resolved.

**Comment by michael-o** [comment]
> I have not deliberately changed anything about being more strict with section nesting, I think we should still allow starting with an h2. Could be an unintended side effect of fixing the nesting levels. Do we have a minimum example in MD? Any warning emitted?

Minimal MD without any output and broken HTML:
```
## Introduction

Foo
```
output:
```´
        <main id="bodyColumn" class="span10">
<section>
        </main>
```

**Comment by michael-o** [comment]
I will factor out the document fixes first...

**Comment by kwin** [comment]
I think it is time for an update again. @michael-o Do you take it up or should I take over to bump to latest m-site-p and fluido 2?

**Comment by michael-o** [comment]
> I think it is time for an update again. @michael-o Do you take it up or should I take over to bump to latest m-site-p and fluido 2?

Let me finish Fluido release today first.

**Comment by ditbace** [comment]
sure thank you

**Comment by michael-o** [comment]
@kwin skin is on Central, you can upgrade this PR.

**Comment by kwin** [comment]
I just did, pushed the updated and cross-checked the result. Looks good to me. @slawekjaranowski Would you mind having another look?

**Review by kwin — APPROVED** [review]

**Review by slawekjaranowski — COMMENTED** [review]
In the most pages looks ok, 
one issue I found - lost anchors with toc at https://maven.apache.org/settings.html

**Comment by kwin** [comment]
Ok found one regression with table headers, they are by default centered and no longer left-aligned: 

Screenshot 2024-11-07 at 17 47 51

This seems to have regressed with https://github.com/apache/maven-fluido-skin/commit/85123d7be9f42c98712ff94e18619095ab284a9f. @michael-o Any idea?

**Comment by kwin** [comment]
> lost anchors with toc at https://maven.apache.org/settings.html

The anchor format changed (using uppercase), unfortunately https://github.com/apache/maven-site/blob/e225ba9c417830bea36e03285ec52f8330790d07/content/markdown/settings.md?plain=1#L20 uses no macro but a hardcoded list and relies on implementation details of the anchor format.

**Comment by kwin** [comment]
If there is no further concerns, I am gonna merge tomorrow. The table column alignment has been meanwhile clarified in https://issues.apache.org/jira/browse/MSKINS-230.

**Comment by michael-o** [comment]
> If there is no further concerns, I am gonna merge tomorrow. The table column alignment has been meanwhile clarified in https://issues.apache.org/jira/browse/MSKINS-230.

Go ahead

**Pull request merged**
