### PR TITLE
fixed the URL referred to in the documentation

### PR DESCRIPTION
**Pull request by pradeepanchan**
The repo url did not match that mentioned in the POM.xml

### CODE REVIEW

**Comment by hboutemy** [comment]
where are you looking at?
see https://maven.apache.org/ref/3.6.0/maven-model-builder/super-pom.html or https://maven.apache.org/ref/3.0.5/maven-model-builder/super-pom.html

**Comment by pradeepanchan** [comment]
I noticed it here: https://maven.apache.org/guides/introduction/introduction-to-the-pom.html

**Comment by hboutemy** [comment]
ok, I see: this section of introduction to the pom should be updated with Maven 3.x version of super-pom
these old versions for Maven 2.0 or 2.1 are really obsolete now

**Comment by slachiewicz** [comment]
Thank you @pradeepanchan for finding inconsistencies in the links.
I have made changes in 53798cc27aea3c67e4a2ece87e9d0e7fc0e47d4e, so that I use the newest pom from 3.5.4. Later versions did not make any changes to this file.
We can close this PR because it is no longer valid. 
I invite you to review and make comments and corrections that are always welcome. We apologize for waiting for a response.

**Pull request closed without merging**
