### PR TITLE
Addition of Cloudsmith Package to repo-management page

### PR DESCRIPTION
**Pull request by alancarson**
Please add Cloudsmith to the list of Repository Services. Thank you!

### CODE REVIEW

**Comment by lskillen** [comment]
@olamy Hi Olivier - It would be really appreciated if this was merged, and we'll be eternally thankful. :-)

We're a fully-fledged Maven (and many others) repository service and we offer generous free (and free for Open-Source) tiers for users in addition to the commercial tiers.

Thank you!

**Comment by hboutemy** [comment]
sorry for the delay: was not able to commit when saw it, but forgot after that

merged (on svn origin)

**Comment by lskillen** [comment]
@hboutemy Don't worry about the delay, you're still awesome - Thank you!

**Comment by alancarson** [comment]
Thanks Hervé - much appreciated!

**Pull request closed without merging**
