### PR TITLE
[MNGSITE-343] doc updated to be more clear about the plugin management

### PR DESCRIPTION
**Pull request by eramol**
doc updated to be more clear about the plugin management usage

### CODE REVIEW

**Comment by khmarbaise** [comment]
First I have moved the issue to the correct location https://issues.apache.org/jira/browse/MNGSITE-343 and it would be great if you could change your commit message accordingly ...and I would appreciate to merge you fix....

**Comment by eramol** [comment]
changed the commit message

**Comment by khmarbaise** [comment]
Thanks for you contribution. 
* Merged into master https://gitbox.apache.org/repos/asf?p=maven-site.git;a=commitdiff;h=114afddb4d4a9bd7a1de3c3c60c9f5a34c73fd8e
* https://issues.apache.org/jira/browse/MNGSITE-343 (closed).
will be online with a few minutes...Thanks.

**Comment by jira-importer** [comment]
Resolve #934

**Pull request closed without merging**
