### PR TITLE
[MNGSITE-412] Add Reposilite to the list of available repository managers

### PR DESCRIPTION
**Pull request by dzikoysk**
#[MNGSITE-412](https://issues.apache.org/jira/browse/MNGSITE-412)
Project: https://github.com/dzikoysk/reposilite

### CODE REVIEW

**Comment by michael-o** [comment]
@rfscholte Does this infringe our Maven name?

**Comment by dzikoysk** [comment]
Oh, good point actually 🤔 

`You can choose to release the modified or derived products under different licenses, the unmodified parts of the software, however, must retain the Apache License, and you cannot name your modified version in any way that suggests that the final product is endorsed or created by the ASF.`

I didn't think about the name, I've just merged two names of used libraries: NanoHttpd + Maven. Let me know if it is a problem and I'll just change it.

**Comment by slachiewicz** [comment]
Project looks active only in last month, website, hosting repo site - not very clear about how to use it, who manages it etc.

**Comment by khmarbaise** [comment]
I opened already some issues related the usage/docs but I find that a very interesting project. Apart from that I don't think it violates legals (I'm not a lawyer).
The activity has been in 2020, 2019, 2018. Like a usual open source project.

**Comment by dzikoysk** [comment]
> 
> Project looks active only in last month, website, hosting repo site - not very clear about how to use it, who manages it etc.

This is just a minimal project without a sugar. If it worked properly, there was no need to apply changes. In case of any problems I've also provided fast support - https://twitter.com/pawelantczak/status/1047925217622994945. I was also focused on another similar project - [reposilite](https://github.com/panda-lang/reposilite). I've changed my plans lately and it is why there is such a high activity above average.

The whole guide is available in README. I'm pretty sure that at this moment it covers almost all of the implemented features - just remember, it allocates 4MB of RAM.

**Comment by rfscholte** [comment]
I do think the name conflicts. NanoMaven is clearly referring to Apache Maven, but it is unclear that the project is not part of Apache Maven. To prevent any possible confusion, the project should have a different name.
As this is about an artifact repository manager, there's no need to refer to Maven at all.

**Comment by dzikoysk** [comment]
I agree that the name was referring to Apache Maven, but I don't think it makes any confusion, it's like saying that GitHub or GitLab is a part of Git and its specification 🤷 Without further ado, it just conflicts with the license and it is why I've already changed. I also changed the url with the latest commit (at this moment forwarded to github repository).

**Comment by dzikoysk** [comment]
Any thoughts on that? :)

**Comment by jira-importer** [comment]
Resolve #985

**Pull request closed without merging**
