### PR TITLE
Fix section indents

### PR DESCRIPTION
**Pull request by michael-o**
Factored out from the other PR.

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
@michael-o there is a problem with special chars ... they are not escaped / removed by the plexus-xml

**Comment by michael-o** [comment]
> @michael-o there is a problem with special chars ... they are not escaped / removed by the plexus-xml

Which?

**Comment by slawekjaranowski** [comment]
last comments was on wrong PR ...

**Comment by michael-o** [comment]
@slawekjaranowski Are we good to merge this or you need more time to review? No issue, if so.

**Review by slawekjaranowski — APPROVED** [review]

**Pull request merged**
