### PR TITLE
[MNGSITE-430] add dependency POMs

### PR DESCRIPTION
**Pull request by hboutemy**

### CODE REVIEW

**Review by aheritier — APPROVED** [review]

**Comment by rfscholte** [comment]
I suggest to split this up into two: 
- The repository resolution order for a local/reactor pom
- The repository resolution order for a dependency pom

It must be very clear that transitive dependencies are never effected by repos of their calling pom.

**Comment by hboutemy** [comment]
@rfscholte local POM does not have any resolution: it is locally on disk, from Git
resolution is always for dependencies

> transitive dependencies are never effected by repos of their calling pom.
they are affected by repos of their calling pom, that is exactly what resolution order is about

**Comment by rfscholte** [comment]
The last description is still not clear for me. I think what we're trying to say: repositories within context, i.e the reposities of the pom that defined this pom as a dependency.

**Comment by hboutemy** [comment]
yes, the last description is the hard one where we need creativity...

"POMs from dependency path to the artifact"?

**Comment by rfscholte** [comment]
Sometimes images say more than words. Looks like this one should have a picture of a graph to support the logic.

**Comment by hboutemy** [comment]
yes, we can add such an image in a future step

**Comment by jira-importer** [comment]
Resolve #997

**Pull request merged**
