### PR TITLE
Using an SPDX identifier as the license name in example

### PR DESCRIPTION
**Pull request by slawekjaranowski**
According to recommendation a few lines below

### CODE REVIEW

**Review by michael-o — COMMENTED** [review]
Looking at https://spdx.org/licenses/ it differentiates between name and id. Here, we abuse our name as id. I consider this to be logically wrong.

**Comment by slawekjaranowski** [comment]
> Looking at https://spdx.org/licenses/ it differentiates between name and id. Here, we abuse our name as id. I consider this to be logically wrong.

We have text:

> Using an https://spdx.org/licenses/}SPDX identifier as the license `name` is recommended.

So how should be ...

I merged similar in ASF parent pom 😄

**Comment by michael-o** [comment]
> > Looking at https://spdx.org/licenses/ it differentiates between name and id. Here, we abuse our name as id. I consider this to be logically wrong.
> 
> We have text:
> 
> > Using an [https://spdx.org/licenses/}SPDX](https://spdx.org/licenses/%7DSPDX) identifier as the license `name` is recommended.
> 
> So how should be ...
> 
> I merged similar in ASF parent pom 😄

I know that we have it and only because we don't have an id element. For me, it feels wrong, honestly, but I won't object to merge it.

**Comment by kwin** [comment]
For me id is more useful than an arbitrary label. Therefore I think we should stick to using an id in the name element (although the naming of the element is unfortunate)

**Review by kwin — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #1095

**Pull request merged**
