### PR TITLE
Remove java 6 instructions

### PR DESCRIPTION
**Pull request by elharo**
@hboutemy Given that we're now discussing whether we can require Java 8, I think it's safe to remove instructions on whether and how it's OK to require Java 6 in a plugin.

### CODE REVIEW

**Comment by khmarbaise** [comment]
Currently we have only decided to use JDK8 for Maven Core 3.7.0+ not yet talked/discussed about plugins etc. to lift the minimum as well...

**Comment by elharo** [comment]
Yes, but do we require special steps for those plugins to use Java 6? I think we're assuming at least java 7 everywhere.

**Comment by khmarbaise** [comment]
Yes of course this is correct. So yes JDK6 is obsolete. No one should use JDK6 to develop a plugin ...anymore ...

**Comment by slachiewicz** [comment]
Maybe we can only rename/replace Java 6 with Java 7 (plus redirect from old one)? If we assume 7 all information is still valid.

**Comment by elharo** [comment]
Thanks. Looks like I'm not listed as a committer in this repo yet so someone else will have to merge.

**Pull request merged**
