### PR TITLE
Add 3.7.0 reactor changes

### PR DESCRIPTION
**Pull request by MartinKanters**
In 3.7.0 multiple improvements have been done to the reactor in Maven. 
This PR described changed behaviour and new features.

### CODE REVIEW

**Review by mthmulders — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by michael-o — APPROVED** [review]

**Comment by mickroll** [comment]
Is there a roadmap for the 3.7.0 release? Some of the improvements are important to downstream projects.

**Comment by MartinKanters** [comment]
As far as I know there is no roadmap for the next release set, sorry for that.

**Comment by MartinKanters** [comment]
Superseded by https://github.com/apache/maven-site/pull/236

**Pull request closed without merging**
